import {
  AlarmClock,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  AppWindow,
  Archive,
  ArrowDown,
  ArrowDownToLine,
  ArrowDownUp,
  ArrowDownWideNarrow,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpNarrowWide,
  AtSign,
  BadgeAlert,
  BadgeCheck,
  BadgeHelp,
  BadgeInfo,
  Banknote,
  Bell,
  BellDot,
  BellMinus,
  BellOff,
  BellPlus,
  BellRing,
  Bitcoin,
  Blend,
  Bold,
  Book,
  BookOpen,
  Bookmark,
  BookmarkCheck,
  BookmarkPlus,
  Box,
  Braces,
  Briefcase,
  Bug,
  Calendar,
  CalendarCheck,
  CalendarDays,
  CalendarMinus,
  CalendarPlus,
  CalendarRange,
  CalendarX,
  Camera,
  ChartBar,
  ChartColumn,
  ChartLine,
  ChartPie,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDown,
  ChevronsDownUp,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  ChevronsUpDown,
  Circle,
  CircleAlert,
  CircleCheck,
  CloudAlert,
  CloudCheck,
  CircleChevronDown,
  CircleChevronLeft,
  CircleChevronRight,
  CircleChevronUp,
  CircleDollarSign,
  CircleDot,
  CircleHelp,
  CircleMinus,
  CirclePause,
  CirclePlay,
  CirclePlus,
  CircleStop,
  CircleUserRound,
  CircleX,
  Clapperboard,
  Clock,
  Cloud,
  CloudDownload,
  CloudOff,
  CloudUpload,
  Code,
  Coffee,
  Columns2,
  Columns3,
  Command,
  Compass,
  Cookie,
  Copy,
  CreditCard,
  Crown,
  Database,
  Download,
  Droplet,
  Ellipsis,
  EllipsisVertical,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileCheck,
  FileCode,
  FileDown,
  FileMinus,
  FilePen,
  FilePenLine,
  FilePlus,
  FileSearch,
  FileSliders,
  FileText,
  FileUp,
  FileX,
  Files,
  Filter,
  FilterX,
  Flag,
  Folder,
  FolderCheck,
  FolderCode,
  FolderDown,
  FolderMinus,
  FolderOpen,
  FolderPen,
  FolderPlus,
  FolderSearch,
  FolderUp,
  FolderX,
  Folders,
  Forward,
  Frame,
  Gift,
  Globe,
  Grip,
  GripHorizontal,
  GripVertical,
  HandCoins,
  Hash,
  Heading,
  Heading1,
  Heading2,
  Heading3,
  Heading4,
  Heading5,
  Heading6,
  Headphones,
  Heart,
  History,
  House,
  HousePlus,
  IdCard,
  Image,
  ImageOff,
  Infinity,
  Info,
  Italic,
  Key,
  KeyRound,
  Keyboard,
  Languages,
  Laptop,
  LayoutDashboard,
  LayoutGrid,
  Layers,
  Leaf,
  Lightbulb,
  Link,
  Link2,
  Link2Off,
  List,
  ListChecks,
  ListOrdered,
  ListPlus,
  ListTodo,
  ListX,
  LoaderCircle,
  Lock,
  LockOpen,
  LogIn,
  LogOut,
  Mail,
  MailOpen,
  MailPlus,
  Map,
  MapPin,
  Maximize2,
  Medal,
  Menu,
  MessageCircle,
  MessageCircleMore,
  MessageCircleOff,
  MessageCirclePlus,
  MessageSquare,
  MessageSquarePlus,
  MessagesSquare,
  Mic,
  MicOff,
  Minimize2,
  Minus,
  Monitor,
  MonitorPlay,
  MonitorSmartphone,
  Moon,
  Mouse,
  Move,
  MoveHorizontal,
  MoveVertical,
  Navigation,
  Newspaper,
  Notebook,
  NotebookText,
  Nut,
  Octagon,
  OctagonAlert,
  Option,
  Orbit,
  Palette,
  PanelLeft,
  PanelRight,
  Paperclip,
  Pause,
  PenLine,
  Pencil,
  PencilLine,
  Phone,
  Pilcrow,
  Pin,
  PinOff,
  Play,
  Plus,
  Podcast,
  Podium,
  Printer,
  Puzzle,
  QrCode,
  Quote,
  Rabbit,
  Rainbow,
  RectangleHorizontal,
  Redo2,
  RefreshCcw,
  RefreshCw,
  Repeat2,
  Rewind,
  RotateCcw,
  Route,
  Rows3,
  Ruler,
  Save,
  Search,
  SearchCheck,
  Send,
  Server,
  Settings,
  Settings2,
  Share,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  SkipBack,
  SkipForward,
  SlidersHorizontal,
  Smartphone,
  Smile,
  Speech,
  Square,
  SquareCheck,
  SquareCheckBig,
  SquareCode,
  SquareMousePointer,
  SquarePen,
  SquarePlus,
  SquareStack,
  SquareTerminal,
  SquareUserRound,
  SquareX,
  Star,
  StickyNote,
  Strikethrough,
  Sun,
  SwatchBook,
  Table,
  Tablet,
  Tag,
  Terminal,
  Text,
  ThumbsDown,
  ThumbsUp,
  Ticket,
  Timer,
  TimerOff,
  Trash,
  Trash2,
  TrendingDown,
  TrendingUp,
  Triangle,
  TriangleAlert,
  Trophy,
  Type,
  Underline,
  Undo2,
  Unlink,
  Upload,
  User,
  UserCheck,
  UserCog,
  UserMinus,
  UserPlus,
  UserX,
  Users,
  UsersRound,
  Video,
  Volume1,
  Volume2,
  VolumeOff,
  VolumeX,
  Wallet,
  WalletCards,
  WandSparkles,
  Wifi,
  WifiLow,
  WifiOff,
  WifiZero,
  Workflow,
  X,
  Zap,
  ZoomIn,
  ZoomOut,
} from "lucide-react";

// F: rendered filled (used for "-bold"/active variants that fill cleanly)
// B: rendered with a heavier stroke (bold variants that don't fill cleanly)
// K: filled with a knockout stroke (stroke painted in the page background color,
//    e.g. the solid verified badge with a white check)
const F = { fill: true };
const B = { bold: true };
const K = { fill: true, knockout: true };

// Intrinsic colors of the original colored SVG assets,
// applied only when the icon is rendered with isColored.
const iconColors = {
  trash: "#FF4A4A",
  "crossmark-tt": "#FF4A4A",
  "logout-red": "#FF4A4A",
  "checkmark-tt": "#00C04D",
  checkmark: "#00C04D",
  protected: "#00C04D",
  "checkmark-c1": "#EE7700",
  "info-tt": "#EE7700",
  "bolt-bold": "#EE7700",
  info: "#EE7700",
  mute: "#FF4A4A",
  unmute: "#FF4A4A",
};

// Icons with no lucide equivalent (brand logos, country flags, colored assets,
// gifs, the YakiHonne logos...) are intentionally absent from these maps; the
// Icon component falls back to the original image rendering for them.
const lucideIconsV1 = {
  "add-curation": FolderPlus,
  "add-note": SquarePen,
  admin: UserCog,
  arrow: ChevronDown,
  "arrow-up": ArrowUp,
  "arrow-up-bold": [ArrowUp, B],
  bold: Bold,
  bolt: Zap,
  "bolt-bold": [Zap, F],
  bookmark: BookmarkPlus,
  "bookmark-24-b": [BookmarkCheck, F],
  "bookmark-b": [BookmarkCheck, F],
  "bookmark-i": Bookmark,
  "bookmark-i-b": [Bookmark, F],
  "bookmark-i-bold": [Bookmark, F],
  bounties: HandCoins,
  "broken-image": ImageOff,
  bug: Bug,
  "bunny-icon": Rabbit,
  "burger-menu": Menu,
  button: SquareMousePointer,
  buzz: Box,
  "buzz-bold": [Box, B],
  cache: Database,
  calendar: Calendar,
  cancel: X,
  categories: LayoutGrid,
  check: Check,
  checkmark: CircleCheck,
  "checkmark-c1": [BadgeCheck, K],
  "checkmark-tt": CircleCheck,
  clone: Blend,
  code: Code,
  comment: MessageCircle,
  "comment-icon": MessageCircle,
  "comment-not": MessageCircleOff,
  connect: LogIn,
  "container-one": RectangleHorizontal,
  "container-one-one": Columns2,
  "container-one-two": PanelRight,
  "container-two-one": PanelLeft,
  "content-s": FileSliders,
  copy: Copy,
  "crossmark-tt": CircleX,
  cup: Trophy,
  curation: Layers,
  "curation-bold": [Layers, B],
  "curation-plus": FolderPlus,
  custom: WandSparkles,
  dashboard: LayoutDashboard,
  "dashboard-bold": [LayoutDashboard, F],
  "deposit-sats": ArrowDownToLine,
  discover: Compass,
  "discover-bold": [Compass, B],
  download: Download,
  "download-file": FileDown,
  edit: Pencil,
  emoji: Smile,
  env: Mail,
  "env-bold": [Mail, B],
  "env-edit": MailPlus,
  export: FileUp,
  "eye-closed": EyeOff,
  "eye-opened": Eye,
  "failed-events": CloudAlert,
  filter: Filter,
  flag: Flag,
  folder: Folder,
  "folder-bold": [Folder, F],
  followings: Users,
  frames: Frame,
  gift: Gift,
  globe: Globe,
  hashtag: Hash,
  heart: Heart,
  "heart-bold": [Heart, F],
  home: House,
  "home-bold": [House, F],
  image: Image,
  infinity: Infinity,
  info: Info,
  "info-flag": BadgeInfo,
  "info-tt": Info,
  italic: Italic,
  "key-icon": KeyRound,
  layers: Layers,
  layout: LayoutDashboard,
  lightning: Zap,
  like: ThumbsUp,
  "like-bold": [ThumbsUp, F],
  link: Link,
  logout: LogOut,
  "logout-red": LogOut,
  medal: Medal,
  media: Clapperboard,
  "media-bold": [Clapperboard, B],
  menu: LayoutGrid,
  mobile: Smartphone,
  "msg-bubbles": MessagesSquare,
  "msg-icon": MessageCircle,
  mute: MicOff,
  news: Newspaper,
  "news-bold": [Newspaper, B],
  "news-plus": Newspaper,
  nip05: BadgeCheck,
  note: StickyNote,
  "note-2": NotebookText,
  "note-2-bold": [NotebookText, B],
  "note-bold": [StickyNote, F],
  "note-plus": SquarePen,
  "nut-zap": Nut,
  orbit: Orbit,
  "orbit-bold": [Orbit, B],
  pin: Pin,
  plain: Type,
  play: Play,
  "play-b": [Play, F],
  "play-bold": [Play, F],
  "play-plus": Play,
  "play-vid": CirclePlay,
  "plus-sign": Plus,
  "plus-sign-w": Plus,
  podcast: Podcast,
  polls: ChartBar,
  posts: FileText,
  "posts-bold": [FileText, B],
  "posts-plus": FilePlus,
  protected: ShieldCheck,
  "protected-2": Shield,
  "pub-hex": Key,
  qrcode: QrCode,
  quote: Quote,
  "quote-bold": [Quote, F],
  "raw-event": Braces,
  recent: Clock,
  "recent-wr": History,
  "redeem-ecash": Banknote,
  report: OctagonAlert,
  republish: RefreshCcw,
  restore: RotateCcw,
  ringbell: Bell,
  "ringbell-bold": [Bell, F],
  sats: Bitcoin,
  search: Search,
  send: Send,
  "send-ecash": CircleDollarSign,
  server: Server,
  setting: Settings,
  "share-icon": ExternalLink,
  "share-icon-2": Share2,
  "share-v2": Share,
  "smart-widget": Puzzle,
  "smart-widget-add": Puzzle,
  "smart-widget-bold": [Puzzle, F],
  "smart-widget-checker": SearchCheck,
  "smart-widget-draft": FilePen,
  star: Star,
  "star-bold": [Star, F],
  "star-boldt": [Star, F],
  stories: BookOpen,
  "succeeded-events": CloudCheck,
  success: CircleCheck,
  "switch-arrows": Repeat2,
  "switch-arrows-bold": [Repeat2, B],
  "switch-arrows-v2": RefreshCw,
  text: Text,
  theme: Palette,
  thumbsdown: ThumbsDown,
  thumbsup: ThumbsUp,
  timeline: Rows3,
  title: Heading,
  "total-events": Cloud,
  translate: Languages,
  trash: Trash2,
  "trending-up": TrendingUp,
  undo: Undo2,
  unmute: Mic,
  unpin: PinOff,
  unprotected: ShieldOff,
  "upload-file": Upload,
  user: User,
  "user-bold": [User, F],
  "user-followed": UserCheck,
  "user-followed-w": UserCheck,
  "user-to-follow": UserPlus,
  "user-to-unfollow": UserMinus,
  video: Video,
  "video-pause": CirclePause,
  "video-play": CirclePlay,
  views: Eye,
  "volume-muted": VolumeX,
  "volume-normal": Volume2,
  wallet: Wallet,
  "wallet-add": WalletCards,
  "wallet-confirm": Wallet,
  warning: TriangleAlert,
  write: PenLine,
  crown: Crown,
  "grid-4": LayoutGrid,
  "grid-2": Columns2,
  workflow: Workflow,
  podium: Podium,
};

const lucideIconsV2 = {
  add_plus: Plus,
  add_plus_circle: CirclePlus,
  add_plus_square: SquarePlus,
  alarm: AlarmClock,
  archive: Archive,
  arrow_down_lg: ArrowDown,
  arrow_down_md: ArrowDown,
  arrow_down_sm: ArrowDown,
  arrow_down_up: ArrowDownUp,
  arrow_left_lg: ArrowLeft,
  arrow_left_md: ArrowLeft,
  arrow_left_right: ArrowLeftRight,
  arrow_left_sm: ArrowLeft,
  arrow_reload_02: RefreshCw,
  arrow_right_lg: ArrowRight,
  arrow_right_md: ArrowRight,
  arrow_right_sm: ArrowRight,
  arrow_up_lg: ArrowUp,
  arrow_up_md: ArrowUp,
  arrow_up_sm: ArrowUp,
  arrows_reload_01: RefreshCcw,
  bell: Bell,
  bell_add: BellPlus,
  bell_close: BellOff,
  bell_notification: BellDot,
  bell_off: BellOff,
  bell_remove: BellMinus,
  bell_ring: BellRing,
  bold: Bold,
  book: Book,
  book_open: BookOpen,
  bookmark: Bookmark,
  bulb: Lightbulb,
  calendar: Calendar,
  calendar_add: CalendarPlus,
  calendar_check: CalendarCheck,
  calendar_close: CalendarX,
  calendar_days: CalendarDays,
  calendar_event: CalendarRange,
  calendar_remove: CalendarMinus,
  calendar_week: CalendarRange,
  camera: Camera,
  caret_circle_down: CircleChevronDown,
  caret_circle_left: CircleChevronLeft,
  caret_circle_right: CircleChevronRight,
  caret_circle_up: CircleChevronUp,
  caret_down_md: ChevronDown,
  caret_down_sm: ChevronDown,
  caret_left_sm: ChevronLeft,
  caret_right_sm: ChevronRight,
  caret_up_md: ChevronUp,
  caret_up_sm: ChevronUp,
  chart_bar_horizontal_01: ChartBar,
  chart_bar_vertical_01: ChartColumn,
  chart_line: ChartLine,
  chart_pie: ChartPie,
  chat: MessageSquare,
  chat_add: MessageSquarePlus,
  chat_circle: MessageCircle,
  chat_circle_add: MessageCirclePlus,
  chat_circle_dots: MessageCircleMore,
  chat_conversation: MessagesSquare,
  chat_dots: MessageCircleMore,
  check: Check,
  check_all: CheckCheck,
  check_all_big: CheckCheck,
  check_big: Check,
  checkbox_check: SquareCheck,
  checkbox_fill: SquareCheckBig,
  checkbox_unchecked: Square,
  chevron_down: ChevronDown,
  chevron_down_duo: ChevronsDown,
  chevron_left: ChevronLeft,
  chevron_left_duo: ChevronsLeft,
  chevron_left_md: ChevronLeft,
  chevron_right: ChevronRight,
  chevron_right_duo: ChevronsRight,
  chevron_right_md: ChevronRight,
  chevron_up: ChevronUp,
  chevron_up_duo: ChevronsUp,
  circle: Circle,
  circle_check: CircleCheck,
  circle_help: CircleHelp,
  circle_warning: CircleAlert,
  clock: Clock,
  close_circle: CircleX,
  close_lg: X,
  close_md: X,
  close_sm: X,
  close_square: SquareX,
  cloud: Cloud,
  cloud_download: CloudDownload,
  cloud_off: CloudOff,
  cloud_upload: CloudUpload,
  code: Code,
  coffee: Coffee,
  columns: Columns3,
  command: Command,
  compass: Compass,
  cookie: Cookie,
  copy: Copy,
  credit_card_01: CreditCard,
  credit_card_02: CreditCard,
  data: Database,
  desktop: Monitor,
  devices: MonitorSmartphone,
  double_quotes_l: Quote,
  double_quotes_r: Quote,
  download: Download,
  drag_horizontal: GripHorizontal,
  drag_vertical: GripVertical,
  edit_pencil_01: Pencil,
  edit_pencil_02: PencilLine,
  edit_pencil_line_01: PenLine,
  edit_pencil_line_02: PencilLine,
  exit: LogOut,
  expand: Maximize2,
  external_link: ExternalLink,
  file_add: FilePlus,
  file_blank: File,
  file_check: FileCheck,
  file_close: FileX,
  file_code: FileCode,
  file_document: FileText,
  file_download: FileDown,
  file_edit: FilePenLine,
  file_remove: FileMinus,
  file_search: FileSearch,
  file_upload: FileUp,
  files: Files,
  filter: Filter,
  filter_off: FilterX,
  flag: Flag,
  folder: Folder,
  folder_add: FolderPlus,
  folder_check: FolderCheck,
  folder_close: FolderX,
  folder_code: FolderCode,
  folder_document: Folder,
  folder_download: FolderDown,
  folder_edit: FolderPen,
  folder_open: FolderOpen,
  folder_remove: FolderMinus,
  folder_search: FolderSearch,
  folder_upload: FolderUp,
  folders: Folders,
  font: Type,
  forward: Forward,
  gift: Gift,
  globe: Globe,
  hamburger_lg: Menu,
  hamburger_md: Menu,
  handbag: ShoppingBag,
  heading: Heading,
  heading_h1: Heading1,
  heading_h2: Heading2,
  heading_h3: Heading3,
  heading_h4: Heading4,
  heading_h5: Heading5,
  heading_h6: Heading6,
  headphones: Headphones,
  heart_01: Heart,
  heart_02: Heart,
  help: CircleHelp,
  hide: EyeOff,
  house_01: House,
  house_02: House,
  house_03: House,
  house_add: HousePlus,
  image_01: Image,
  image_02: Image,
  info: Info,
  italic: Italic,
  keyboard: Keyboard,
  label: Tag,
  laptop: Laptop,
  layer: Layers,
  layers: Layers,
  leaf: Leaf,
  link: Link,
  link_break: Unlink,
  link_horizontal: Link2,
  link_horizontal_off: Link2Off,
  link_vertical: Link,
  list_add: ListPlus,
  list_check: ListChecks,
  list_checklist: ListTodo,
  list_ordered: ListOrdered,
  list_remove: ListX,
  list_unordered: List,
  loading: LoaderCircle,
  lock: Lock,
  lock_open: LockOpen,
  log_out: LogOut,
  magnifying_glass_minus: ZoomOut,
  magnifying_glass_plus: ZoomIn,
  mail: Mail,
  mail_open: MailOpen,
  map: Map,
  map_pin: MapPin,
  mention: AtSign,
  menu_alt_01: Menu,
  menu_alt_02: Menu,
  menu_alt_03: Menu,
  menu_alt_04: Menu,
  menu_alt_05: Menu,
  menu_duo_lg: Menu,
  menu_duo_md: Menu,
  mobile: Smartphone,
  mobile_button: Smartphone,
  monitor: Monitor,
  monitor_play: MonitorPlay,
  moon: Moon,
  more_grid_big: Grip,
  more_grid_small: Grip,
  more_horizontal: Ellipsis,
  more_vertical: EllipsisVertical,
  mouse: Mouse,
  move: Move,
  move_horizontal: MoveHorizontal,
  move_vertical: MoveVertical,
  navigation: Navigation,
  note: StickyNote,
  note_edit: SquarePen,
  note_search: FileSearch,
  notebook: Notebook,
  octagon: Octagon,
  octagon_warning: OctagonAlert,
  option: Option,
  paper_plane: Send,
  paperclip_attechment_horizontal: Paperclip,
  paperclip_attechment_tilt: Paperclip,
  paragraph: Pilcrow,
  path: Route,
  pause: Pause,
  pause_circle: CirclePause,
  phone: Phone,
  planet: Orbit,
  play: Play,
  play_circle: CirclePlay,
  printer: Printer,
  puzzle: Puzzle,
  qr_code: QrCode,
  radio_fill: CircleDot,
  radio_unchecked: Circle,
  rainbow: Rainbow,
  redo: Redo2,
  remove_minus: Minus,
  remove_minus_circle: CircleMinus,
  rewind: Rewind,
  rows: Rows3,
  ruler: Ruler,
  save: Save,
  search_magnifying_glass: Search,
  select_multiple: SquareStack,
  settings: Settings,
  settings_future: Settings2,
  share_android: Share2,
  share_ios_export: Share,
  shield: Shield,
  shield_check: ShieldCheck,
  shield_warning: ShieldAlert,
  shopping_bag_01: ShoppingBag,
  shopping_bag_02: ShoppingBag,
  shopping_cart_01: ShoppingCart,
  shopping_cart_02: ShoppingCart,
  show: Eye,
  shrink: Minimize2,
  shuffle: Shuffle,
  single_quotes_l: Quote,
  single_quotes_r: Quote,
  skip_back: SkipBack,
  skip_forward: SkipForward,
  slider_01: SlidersHorizontal,
  slider_02: Settings2,
  slider_03: SlidersHorizontal,
  sort_ascending: ArrowUpNarrowWide,
  sort_descending: ArrowDownWideNarrow,
  square: Square,
  square_check: SquareCheck,
  square_help: CircleHelp,
  square_warning: TriangleAlert,
  star: Star,
  stop: Square,
  stop_circle: CircleStop,
  stop_sign: OctagonAlert,
  strikethrough: Strikethrough,
  suitcase: Briefcase,
  sun: Sun,
  swatches_palette: SwatchBook,
  table: Table,
  tablet: Tablet,
  tablet_button: Tablet,
  tag: Tag,
  terminal: Terminal,
  text: Text,
  text_align_center: AlignCenter,
  text_align_justify: AlignJustify,
  text_align_left: AlignLeft,
  text_align_right: AlignRight,
  ticket_voucher: Ticket,
  timer: Timer,
  timer_add: Timer,
  timer_close: TimerOff,
  timer_remove: TimerOff,
  trash_empty: Trash,
  trash_full: Trash2,
  trending_down: TrendingDown,
  trending_up: TrendingUp,
  triangle: Triangle,
  triangle_check: Triangle,
  triangle_warning: TriangleAlert,
  underline: Underline,
  undo: Undo2,
  unfold_less: ChevronsDownUp,
  unfold_more: ChevronsUpDown,
  user_01: User,
  user_02: User,
  user_03: User,
  user_add: UserPlus,
  user_card_id: IdCard,
  user_check: UserCheck,
  user_circle: CircleUserRound,
  user_close: UserX,
  user_remove: UserMinus,
  user_square: SquareUserRound,
  user_voice: Speech,
  users: Users,
  users_group: UsersRound,
  volume_max: Volume2,
  volume_min: Volume1,
  volume_minus: Volume1,
  volume_off: VolumeX,
  volume_off_02: VolumeOff,
  volume_plus: Volume2,
  warning: TriangleAlert,
  water_drop: Droplet,
  wavy_check: BadgeCheck,
  wavy_help: BadgeHelp,
  wavy_warning: BadgeAlert,
  wifi_high: Wifi,
  wifi_low: WifiLow,
  wifi_medium: WifiLow,
  wifi_none: WifiZero,
  wifi_off: WifiOff,
  wifi_problem: WifiOff,
  window: AppWindow,
  window_check: AppWindow,
  window_close: AppWindow,
  window_code_block: SquareCode,
  window_sidebar: PanelLeft,
  window_terminal: SquareTerminal,
};

const getLucideIcon = (name, v) => {
  const entry = v === 2 ? lucideIconsV2[name] : lucideIconsV1[name];
  if (!entry) return null;
  const [Component, options] = Array.isArray(entry) ? entry : [entry, {}];
  return {
    Component,
    fill: !!options.fill,
    bold: !!options.bold,
    knockout: !!options.knockout,
    color: iconColors[name],
  };
};

export { getLucideIcon };
